// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function Budgets():Promise<Array<main.Budget>>;

export function FatalErrorDialog(arg1:context.Context,arg2:Error):Promise<void>;

export function Greet(arg1:string):Promise<string>;
