// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Budgets() {
  return window['go']['main']['App']['Budgets']();
}

export function FatalErrorDialog(arg1, arg2) {
  return window['go']['main']['App']['FatalErrorDialog'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
