// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BudgetList():Promise<Array<main.Budget>>;

export function Categories():Promise<Array<main.Category>>;

export function CreateBudget(arg1:main.Budget):Promise<void>;

export function CreateCategory(arg1:main.Category):Promise<void>;

export function CreateTransaction(arg1:main.CreateTransactionRequest):Promise<void>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function Transactions():Promise<Array<main.Transaction>>;
