// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BudgetList() {
  return window['go']['main']['App']['BudgetList']();
}

export function Categories() {
  return window['go']['main']['App']['Categories']();
}

export function CreateBudget(arg1) {
  return window['go']['main']['App']['CreateBudget'](arg1);
}

export function CreateCategory(arg1) {
  return window['go']['main']['App']['CreateCategory'](arg1);
}

export function CreateTransaction(arg1) {
  return window['go']['main']['App']['CreateTransaction'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function Transactions() {
  return window['go']['main']['App']['Transactions']();
}
